// @ts-nocheck
import { useEffect, useState } from 'react';
import { supabase } from '../db';

export default function Dashboard() {
  const [applicants, setApplicants] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);
  const [showHistoryId, setShowHistoryId] = useState(null);
  const [filterStatus, setFilterStatus] = useState('All');
  const [editId, setEditId] = useState(null);
  const [editData, setEditData] = useState({});

  const fetchData = async () => {
    try {
      const { data } = await supabase.from('applicants').select('*').order('created_at', { ascending: false });
      setApplicants(data || []);
    } catch (e) { console.error(e); } finally { setLoading(false); }
  };

  useEffect(() => { fetchData(); }, []);

  const getStatusTheme = (status) => {
    const themes = {
      'Hired': 'border-emerald-500 text-emerald-600 bg-emerald-50',
      'Offered': 'border-purple-500 text-purple-600 bg-purple-50',
      'Rejected Offer': 'border-rose-500 text-rose-600 bg-rose-50',
      'Interviewing': 'border-amber-500 text-amber-600 bg-amber-50',
      'Applied': 'border-blue-500 text-blue-600 bg-blue-50'
    };
    return themes[status] || 'border-slate-300 text-slate-600 bg-slate-50';
  };

  const openGoogleCalendar = (app, type = 'INTERVIEW') => {
    // 1. Ask for Date
    const dateInput = window.prompt(`Confirm Date (YYYY-MM-DD):`, new Date().toLocaleDateString('en-CA'));
    if (!dateInput) return;

    // 2. Ask for Time
    const timeInput = window.prompt(`Confirm Start Time (24h format HH:MM):`, "10:00");
    if (!timeInput) return;

    // 3. THE FIX: Format as Local Time (No 'Z', No +0800)
    // Google treats YYYYMMDDTHHMMSS (without suffix) as "Local Time"
    const datePart = dateInput.replace(/-/g, '');
    const timePart = timeInput.replace(/:/g, '');
    
    const startStr = `${datePart}T${timePart}00`;
    
    // Calculate End Time (+1 Hour)
    let [h, m] = timeInput.split(':').map(Number);
    let endH = (h + 1).toString().padStart(2, '0');
    const endStr = `${datePart}T${endH}${m.toString().padStart(2, '0')}00`;

    const title = encodeURIComponent(`${type}: ${app.name} - ${app.job_role}`);
    const details = encodeURIComponent(`Candidate: ${app.name}\nRole: ${app.job_role}\nEmail: ${app.email}\nPhone: ${app.phone}\n\nGenerated by Geniebook ATS`);
    
    // We remove 'ctz' and use the Template action with clean local dates
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${startStr}/${endStr}&details=${details}`;
    
    window.open(url, '_blank');
  };

  const handleStatusChange = async (app, newStatus) => {
    let finalOffer = app.final_offer_salary;
    let onboardingDate = app.onboarding_date;

    if (newStatus === 'Offered') {
      const amount = window.prompt(`Final Offer Salary:`, app.salary_expectation || "");
      if (amount !== null) finalOffer = amount;
    }

    if (newStatus === 'Interviewing' || newStatus === 'Hired') {
      const confirm = window.confirm(`Would you like to schedule the ${newStatus} in Google Calendar?`);
      if (confirm) openGoogleCalendar(app, newStatus.toUpperCase());
    }

    const history = [...(app.status_history || []), { status: newStatus, date: new Date().toISOString() }];
    await supabase.from('applicants').update({ 
      status: newStatus, 
      status_history: history,
      final_offer_salary: finalOffer,
      onboarding_date: onboardingDate
    }).eq('id', app.id);
    fetchData();
  };

  const saveEdit = async () => {
    await supabase.from('applicants').update(editData).eq('id', editId);
    setEditId(null);
    fetchData();
  };

  const activePipeline = applicants.filter(a => !['Quit', 'Blacklisted', 'Failed Interview'].includes(a.status));
  const filtered = activePipeline.filter(a => 
    (a.name.toLowerCase().includes(searchTerm.toLowerCase()) || a.job_role.toLowerCase().includes(searchTerm.toLowerCase())) &&
    (filterStatus === 'All' || a.status === filterStatus)
  );

  if (loading) return <div className="flex h-screen items-center justify-center font-black text-slate-200 animate-pulse tracking-widest text-4xl italic">GENIEBOOK</div>;

  return (
    <div className="max-w-7xl mx-auto px-6 pb-24 space-y-12">
      
      {/* 🚀 CATEGORY TABS */}
      <div className="flex flex-wrap gap-3">
        {['All', 'Applied', 'Interviewing', 'Offered', 'Hired', 'Rejected Offer'].map(s => (
          <button key={s} onClick={() => setFilterStatus(s)} className={`px-6 py-2.5 rounded-full text-[10px] font-black uppercase tracking-[0.2em] transition-all border-2 ${
            filterStatus === s ? 'bg-slate-900 text-white border-slate-900 shadow-2xl' : 'bg-white text-slate-400 border-slate-50 hover:border-slate-200'
          }`}>
            {s === 'Rejected Offer' ? 'Declined' : s} ({s === 'All' ? activePipeline.length : activePipeline.filter(a => a.status === s).length})
          </button>
        ))}
      </div>

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-8 py-10 bg-white border border-slate-50 rounded-[3rem] px-10 shadow-sm">
        <h1 className="text-5xl font-black text-slate-900 tracking-tighter italic">Talent<span className="text-blue-600">.</span></h1>
        <input 
          type="text" 
          placeholder="Search candidates..." 
          className="bg-slate-50 px-8 py-4 rounded-3xl outline-none border-2 border-transparent focus:border-blue-500 w-full md:w-96 font-bold text-lg shadow-inner"
          onChange={e => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
        {filtered.map(app => (
          <div key={app.id} className="bg-white rounded-[3.5rem] border border-slate-100 shadow-2xl shadow-slate-200/60 flex flex-col overflow-hidden transition-all hover:scale-[1.01]">
            
            <div className={`p-10 pb-6 border-t-[16px] ${getStatusTheme(app.status).split(' ')[0]}`}>
              <div className="flex justify-between items-start">
                <div className="flex-grow">
                  {editId === app.id ? (
                    <input className="w-full text-2xl font-black border-b-2 border-blue-400 outline-none mb-2" value={editData.name} onChange={e => setEditData({...editData, name: e.target.value})} />
                  ) : (
                    <h2 className="text-3xl font-black text-slate-800 tracking-tight leading-none">{app.name}</h2>
                  )}
                  <p className="text-[11px] font-black uppercase tracking-[0.2em] text-blue-500 mt-2">{app.job_role}</p>
                </div>
                <button onClick={() => editId === app.id ? saveEdit() : (setEditId(app.id), setEditData(app))} className="p-4 bg-slate-50 rounded-3xl hover:bg-slate-900 hover:text-white transition-all shadow-sm">
                  {editId === app.id ? '💾' : '✏️'}
                </button>
              </div>
            </div>

            <div className="p-10 pt-0 space-y-8 flex-grow">
              {/* Communication Hub */}
              <div className="grid grid-cols-2 gap-4">
                <a href={`mailto:${app.email}`} className="flex items-center justify-center bg-slate-50 p-4 rounded-2xl text-[10px] font-black text-slate-500 hover:bg-slate-900 hover:text-white transition-all">EMAIL</a>
                <a href={`https://wa.me/${app.phone?.replace(/[^0-9]/g, '')}`} target="_blank" className="flex items-center justify-center bg-emerald-50 p-4 rounded-2xl text-[10px] font-black text-emerald-700 hover:bg-emerald-600 hover:text-white transition-all">WHATSAPP</a>
              </div>

              {/* SCHEDULE BUTTON */}
              <button 
                onClick={() => openGoogleCalendar(app, 'INTERVIEW')}
                className="w-full flex items-center justify-center gap-3 py-5 bg-amber-400 text-amber-950 rounded-[2rem] font-black text-[12px] uppercase tracking-widest hover:bg-amber-500 transition-all shadow-lg shadow-amber-100"
              >
                📅 Schedule Slot
              </button>

              <div className="bg-slate-50 p-8 rounded-[2.5rem] border border-slate-100 space-y-5">
                <div className="flex justify-between text-sm font-bold items-center">
                  <span className="text-slate-400 uppercase text-[10px] tracking-widest">Last Drawn</span>
                  {editId === app.id ? <input className="w-24 text-right border-b bg-transparent" value={editData.last_drawn_salary} onChange={e => setEditData({...editData, last_drawn_salary: e.target.value})} /> : <span className="text-slate-700">{app.last_drawn_salary || '—'}</span>}
                </div>
                <div className="flex justify-between text-sm font-black items-center">
                  <span className="text-slate-400 uppercase text-[10px] tracking-widest">Expectation</span>
                  {editId === app.id ? <input className="w-24 text-right border-b bg-transparent" value={editData.salary_expectation} onChange={e => setEditData({...editData, salary_expectation: e.target.value})} /> : <span className="text-blue-600 text-lg">{app.salary_expectation || '—'}</span>}
                </div>
              </div>
            </div>

            <div className="p-10 pt-0 space-y-5">
              <select 
                value={app.status} 
                onChange={e => handleStatusChange(app, e.target.value)} 
                className={`w-full py-5 px-6 rounded-3xl text-[12px] font-black uppercase tracking-widest cursor-pointer border-2 appearance-none text-center ${getStatusTheme(app.status)}`}
              >
                <option value="Applied">Applied</option>
                <option value="Interviewing">Interviewing</option>
                <option value="Offered">Offered</option>
                <option value="Hired">Hired</option>
                <option value="Rejected Offer">Rejected Offer</option>
                <option disabled>── ARCHIVE ──</option>
                <option value="Failed Interview">Failed</option>
                <option value="Quit">Quit</option>
                <option value="Blacklisted">Blacklisted</option>
              </select>

              <div className="flex gap-4">
                <a href={app.resume_metadata?.url} target="_blank" className="flex-1 text-center bg-slate-900 text-white py-5 rounded-3xl font-black text-[11px] tracking-[0.2em] uppercase hover:bg-black transition-all shadow-xl">Resume</a>
                <button onClick={() => setShowHistoryId(showHistoryId === app.id ? null : app.id)} className="px-8 bg-slate-50 rounded-3xl text-slate-300 font-bold hover:text-blue-500 transition-colors">🕒</button>
              </div>
            </div>

            {/* HISTORY LOG */}
            {showHistoryId === app.id && (
              <div className="absolute inset-0 bg-white z-50 p-12 flex flex-col rounded-[3.5rem] shadow-2xl animate-fade-in border-4 border-slate-50">
                <div className="flex justify-between items-center mb-12 border-b pb-6">
                  <span className="text-[12px] font-black text-slate-400 uppercase tracking-[0.3em]">Lifecycle Log</span>
                  <button onClick={() => setShowHistoryId(null)} className="h-12 w-12 flex items-center justify-center rounded-full bg-slate-50 text-slate-400 font-bold hover:text-red-500 transition-all">✕</button>
                </div>
                <div className="flex-grow overflow-y-auto space-y-10">
                  {app.status_history?.map((h, i) => (
                    <div key={i} className="relative pl-10 border-l-4 border-slate-50">
                      <div className="absolute -left-[10px] top-1 w-4 h-4 rounded-full bg-blue-500 shadow-lg shadow-blue-200"></div>
                      <div className="text-sm font-black uppercase text-slate-800 tracking-tight">{h.status}</div>
                      <div className="text-[11px] text-slate-400 font-bold mt-2">{new Date(h.date).toLocaleDateString()}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}